package elevatorsim;

public enum EventType {
	  FLOOR_REQUEST,
	  FLOOR_REQUEST_UP,
	  FLOOR_REQUEST_DOWN,
	  MOVE_REQUEST_UP,
	  MOVE_REQUEST_DOWN,
	  ELEVATOR_ARR_FLOOR_UP,
	  ELEVATOR_ARR_FLOOR_DOWN,
	  ELEVATOR_PICK_FLOOR,
	  ELEVATOR_ARRIVED,
	  OPEN_DOOR,
	  CLOSE_DOOR,
	  OPEN_DOOR_BUTTON_PRESSED,
	  CLOSE_DOOR_BUTTON_PRESSED;
}
