package elevatorsim;

public enum EventType {
	  FLOOR_BUTTON_PRESSED,
	  ACK_FLOOR_BUTTON_PRESSED,
	  RECEIVE_MOVE_REQUEST_UP,
	  RECEIVE_MOVE_REQUEST_DOWN,
	  ELEVATOR_ARR_FLOOR_UP,
	  ELEVATOR_ARR_FLOOR_DOWN,
	  ELEVATOR_PICK_FLOOR,
	  OPEN_DOOR,
	  CLOSE_DOOR,
	  OPEN_DOOR_BUTTON_PRESSED,
	  CLOSE_DOOR_BUTTON_PRESSED;
}
