package ElevatorSim.src.elevatorsim;

public enum EventType {
	  FLOOR_BUTTON_PRESSED,
	  ACK_FLOOR_BUTTON_PRESSED,
	  RECEIVE_MOVE_REQUEST_UP,
	  RECEIVE_MOVE_REQUEST_DOWN
	  OPEN_ELEVATOR_DOOR,
	  ELEVATOR_
}
